User:
  read:
    attributes: [name, gender, description, birthday]
  list:
    attributes: [name, gender]
Post:
  create:
    before:
      set:
        author: me
  read:
    include:
      - as: author
        model: User
        attributes: [name, gender]
  list:
    include:
      - as: author
        model: User
        attributes: [name, gender]