user:
  read:
    attributes: [name, gender]
  list:
    attributes: [name, gender]
hug:
  create:
    before:
      set:
        sender: me
  read:
    where:
      recipient: me
    include:
      - as: sender
        model: User
        attributes: [name, gender]
  list:
    where:
      recipient: me
    include:
      - as: sender
        model: User
        attributes: [name, gender]